# Generated by Django 4.2 on 2023-05-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='preview',
            field=models.ImageField(upload_to='product/previews/%Y/%Y-%m-%d-%H-%M-%S/', verbose_name='Превью товара'),
        ),
    ]
