# Generated by Django 4.2 on 2023-05-17 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofils',
            options={'verbose_name': 'профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
    ]
