# Generated by Django 4.2 on 2023-05-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_userprofils_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'каригорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='userprofils',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
