# Generated by Django 4.2 on 2023-05-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_products_price_products_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Описание товара'),
        ),
    ]
