# Generated by Django 4.2 on 2023-05-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_products_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='top_status',
            field=models.BooleanField(default=False, verbose_name='Промо товар'),
        ),
    ]
