# Generated by Django 4.2 on 2023-05-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_basket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Описание товара'),
        ),
    ]
